theme: jekyll-theme-cayman

title: Flight Mechanics for Pilots
description: Teaching material for student pilots of the Italian Air Force Academy

url: https://github.com/agodemar/FlightMechanics4Pilots
repository: agodemar/FlightMechanics4Pilots
github: [metadata]

markdown: kramdown
mathjax: true

include: ['_mypages']

categories: [mycontent, misc, menu]
