theme: jekyll-theme-cayman
markdown: kramdown
mathjax: true

title: Flight Mechanics for Pilots
description: Teaching material for student pilots of the Italian Air Force Academy

url: https://agodemar.github.io/FlightMechanics4Pilots
repository: agodemar/FlightMechanics4Pilots
# repository: https://github.com/agodemar/FlightMechanics4Pilots
# github: [metadata]

# include: ['_mypages']
defaults:
  - scope:
      path: "_mypages"
      type: "mypages"
    values:
      layout: "mypages"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "_mypages/img_jupyter"
    values:
      image: true

collections:
  mypages:
    permalink: /:collection/:path/
    output: true

categories: [menu, info, content, notebook, references, nomenclature]
